/* eslint-disable @typescript-eslint/no-unused-vars */
import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useEffect, useState } from "react";
import { Data, DataMovie, DataTv } from "../components/interfaces";
import Movie from "./movie";
import Tv from "./tv";
import Header from "./Header";
import Image from "next/image";

async function getData(): Promise<Data> {
  const getMovie = await fetch("/api/mapMovie");
  const movie = await getMovie.json();
  const getTv = await fetch("/api/mapTv");
  const tv = await getTv.json();
  return { movie, tv };
}
interface PropsData {
  movie: DataMovie[];
  tv: DataTv[];
}

export default function Home(): JSX.Element {
  const [data, setData] = useState<PropsData | null>(null);
  const [search, setSearch] = useState([]);
  const [type, setType] = useState(null);
  const [isLoading, setLoading] = useState(true);
  useEffect(() => {
    setSearch(null);
    void (async (): Promise<void> => {
      let _data: any = [];
      _data = await getData();
      setData(_data);
    })();
    setType(true);
  }, []);

  useEffect(() => {
    setSearch(null);
    setTimeout(() => {
      if (data) {
        const num: number = Math.floor(Math.random() * data.tv.length) - 6;
        console.log(num);
        if (type) {
          setSearch(data.movie.slice(num, num + 6));
        } else {
          setSearch(data.tv.slice(num, num + 6));
        }
      }
    }, 100);
  }, [type]);

  function filterData(_data: PropsData, text: string): void {
    setSearch(null);
    if (!_data) {
      return;
    }
    function loop(item: any): any {
      return item.title.toLowerCase().includes(text.toLowerCase());
    }
    if (type) {
      const _filter: any = _data.movie.filter(loop);
      if (_filter?.length > 6) {
        setSearch(_filter.slice(0, 6));
      } else if (_filter.length > 0) {
        setSearch(_filter);
      }
    } else {
      const _filter = _data.tv.filter(loop);
      if (_filter.length > 6) {
        setSearch(_filter.slice(0, 6));
      } else if (_filter.length > 0) {
        setSearch(_filter);
      }
    }
  }
  useEffect(() => {
    if (!data) {
      setLoading(true);
    } else {
      setLoading(false);
    }
  }, [data]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header
          filterData={filterData}
          data={data}
          type={type}
          setType={setType}
        />
        {!isLoading &&
          (type ? <Movie search={search} /> : <Tv search={search} />)}
        {isLoading && (
          <div
            style={{
              width: "100%",
              height: "90vh",
              display: "flex",
              justifyContent: "center",
              alignItems: "center"
            }}
          >
            <Image
              style={{ padding: "auto" }}
              width={100}
              height={100}
              src="https://media.tenor.com/On7kvXhzml4AAAAj/loading-gif.gif"
              alt={"loading"}
            />
          </div>
        )}
      </main>
    </>
  );
}
